name: my_app
description: YOLO → RTMPose → MotionBERT on-device
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.5.1
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  image: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/models/configs/
